AssetMGT/ViewModels/DisposalViewModel.cs
using AssetMGT.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AssetMGT.ViewModels
{
    public class DisposalViewModel
    {
        //public IEnumerable<Asset> Assets { get; set; }
        public IEnumerable<Disposal> Disposals { get; set; }
        

        //enables to have a list of currencies in our viewmodel currencies

        public IEnumerable<SelectListItem> Currencies { get; set; }
        public IEnumerable<SelectListItem> Customers { get; set; }
        public List<Asset> Assets { get; set; }
        public int thePrice { get; set; }

        public IEnumerable<SelectListItem> CustomerId { get; set; }

        public IEnumerable<SelectListItem>  CurrencyId { get; set; }


}
}

AssetMGT/Controllers/DisposalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetMGT.Data;
using AssetMGT.Service;
using AssetMGT.ViewModels;

namespace AssetMGT.Controllers
{
    public class DisposalController : Controller
    {
        private AssetMGTContext db = new AssetMGTContext();

        // GET: Disposal
        [DynamicRoleAuthorize(ControllerName.Disposal, ActionName.Index)]
        public ActionResult Index()
        {
            //var disposals = db.Disposals.Include(d => d.Asset).Include(d => d.Currency).Include(d => d.Customer);
            var disposals = db.Disposals.Include(d => d.Asset);

            //var disposals = db.Disposals.Include(d => d.Asset).Include(a => a.AssetClass).Include(a => a.AssetIndicator).Include(a => a.Employee).Include(a => a.MaintenanceFrequency).Include(a => a.Supplier);

            return View(disposals.ToList());
        }

        // GET: Disposal/Details/5
        [DynamicRoleAuthorize(ControllerName.Disposal, ActionName.Details)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           Disposal disposal = db.Disposals.Find(id);
            ViewBag.DisposalDate = disposal.DisposalDate;
            Asset anAsset = db.Assets.Include(a => a.AssetClass).Include(a => a.AssetIndicator).Include(a => a.Employee).Include(a => a.MaintenanceFrequency).Include(a => a.Supplier).SingleOrDefault(x => x.Id == disposal.AssetId);
            ViewBag.AssetName = anAsset.AssetName;
            if (anAsset == null)
            {
                return HttpNotFound();
            }
            return View(anAsset);
        }

        // GET: Disposal/Create
        //public ActionResult Create(int? id, string DepreciationMethod, int? depPercentage)
        [DynamicRoleAuthorize(ControllerName.Disposal, ActionName.Create)]
        public ActionResult Create(int? id, string[] selectedAssets)
        {
           
            
            if (selectedAssets != null)
            {
                
                foreach (var asset in selectedAssets)
                {
                    Disposal disposal = new Disposal();
                    //disposal.Assets = new List<Asset>();
                    
                    Asset assetToAdd = db.Assets.Find(int.Parse(asset));
                   // disposal.Assets.Add(assetToAdd);
                    
                    assetToAdd.AssetStatus = "Disposed";
                    db.SaveChanges();
                    disposal.DisposalDate = DateTime.UtcNow;
                    disposal.AssetId = assetToAdd.Id;
                    db.Disposals.Add(disposal);
                    db.SaveChanges();

                    //**************Create a transaction here and log the user****************//
                    DateTime dateAndTime = DateTime.Now;
                    string name = HttpContext.User.Identity.Name;
                    ViewBag.Name = name;

                    string action = "Disposed an Asset";
                    string description = "An Asset whose Asset Code is " + assetToAdd.AssetCode + " and Asset Name " + assetToAdd.AssetName + " has been disposed";
                     ActivityLogService activityLogService = new ActivityLogService();
                    activityLogService.LogAction(db, action, description, name, dateAndTime);

                    //*******************End of transaction***********************//
                }
            }
            else
            {
                if(id != null)
                {
                    Disposal disposal = new Disposal();
                    Asset Theasset = db.Assets.Find(id);
                    Theasset.AssetStatus = "Disposed";
                    db.SaveChanges();
                    disposal.DisposalDate = DateTime.UtcNow;
                    disposal.AssetId = Theasset.Id;
                    db.Disposals.Add(disposal);
                    db.SaveChanges();


                    //**************Create a transaction here and log the user****************//
                    DateTime dateAndTime = DateTime.Now;
                    string name = HttpContext.User.Identity.Name;
                    ViewBag.Name = name;                
                    string action = "Disposed an Asset";
                    string description = "An Asset whose Asset Code is " + Theasset.AssetCode + " and Asset Name " + Theasset.AssetName + " has been disposed";
                     ActivityLogService activityLogService = new ActivityLogService();
                    activityLogService.LogAction(db, action, description, name,dateAndTime);

                    //*******************End of transaction***********************//
                }
                else
                {
                    return RedirectToAction("ReadyForDisposal", "Asset");
                }
                
            }

           
           // Disposal disposal = new Disposal();
            

            return RedirectToAction("ReadyForDisposal", "Asset");

            /*
            Asset asset = db.Assets.Where(c=>c.Id == id).Include(w => w.AssetClass).SingleOrDefault();
            DepreciationMethod = asset.DepreciationMethod;
            depPercentage = asset.DepPercentage;

            DisposalViewModel viewModel = new DisposalViewModel();
            if (id != null)
            {
               //send currency and customer list to viewmodel not forgetting the asset list object 
                //viewModel.Currencies = new SelectList(db.Currencies, "Id", "CurrencyCode");
                //viewModel.Customers = new SelectList(db.Customers, "Id", "CustomerName");
                //viewModel.Assets = db.Assets.Where(m => m.Id == id).ToList();

            }*/

            //get the selling price of the asset from the depreciation method
            //DepreciationMethods depreciationMethods = new DepreciationMethods();
            //viewModel.thePrice = depreciationMethods.CalculateDepreciation(id, DepreciationMethod, depPercentage);

            //return View();
        }

        // POST: Disposal/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DynamicRoleAuthorize(ControllerName.Disposal, ActionName.Create)]
        //public ActionResult Create([Bind(Include = "Id,DisposalPrice,disposalStatus,CurrencyId,AssetId,CustomerId")] Disposal disposal)
        public ActionResult Create(string AssetCode, string thePrice, string AssetId, string CurrencyId, string CustomerId)
        {
            int theId = Convert.ToInt32(AssetId);

            /*Asset asset = db.Assets.SingleOrDefault(m => m.Id == theId);
            asset.AssetStatus = "Disposed";*/
            Disposal disposal = new Disposal();
            if (ModelState.IsValid)
                {

                /*Disposal disposedItem = new Disposal();

                disposedItem.CustomerId = disposal.CustomerId;
                disposedItem.AssetId = disposal.AssetName;
                disposedItem.CustomerId = disposal.*/

                Asset asset = db.Assets.SingleOrDefault(m => m.Id == theId);
                asset.AssetStatus = "Disposed";

                disposal.DisposalDate = DateTime.UtcNow;
                    
                    disposal.AssetId = theId;
                /*
                    disposal.DisposalPrice = Convert.ToInt32(thePrice);
                    disposal.CurrencyId = Convert.ToInt32(CurrencyId);
                    disposal.CustomerId = Convert.ToInt32(CustomerId);
                    */

                db.Disposals.Add(disposal);
                    db.SaveChanges();

                return RedirectToAction("Index");
                }

            /*
           ViewBag.AssetId = new SelectList(db.Assets, "Id", "AssetCode", disposal.AssetId);
           ViewBag.CurrencyId = new SelectList(db.Currencies, "Id", "CurrencyName", disposal.CurrencyId);
           ViewBag.CustomerId = new SelectList(db.Customers, "Id", "CustomerName", disposal.CustomerId);
      */

            //ViewBag.DisposalDate = new SelectList(db.Assets.Where(x => x.AssetStatus == "Active"), "Id", "AssetDisposalDate");
            return View(disposal);
        }

        // GET: Disposal/Edit/5
        [DynamicRoleAuthorize(ControllerName.Disposal, ActionName.Edit)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Disposal disposal = db.Disposals.Find(id);
            
            Disposal disposal = db.Disposals.SingleOrDefault(m => m.Id == id);
            int disposedItemId = disposal.AssetId;
            if (disposal == null)
            {
                return HttpNotFound();
            }

            //get the disposed asset details
            Asset asset = db.Assets.SingleOrDefault(m => m.Id == disposedItemId);
            ViewBag.AssetName = asset.AssetName;

            ViewBag.AssetCode = asset.AssetCode;
            ViewBag.AssetId = asset.Id;

            //ViewBag.AssetId = new SelectList(db.Assets, "Id", "AssetCode", disposal.AssetId);
            //ViewBag.CurrencyId = new SelectList(db.Currencies, "Id", "CurrencyName", disposal.CurrencyId);
            //ViewBag.CustomerId = new SelectList(db.Customers, "Id", "CustomerName", disposal.CustomerId);
            return View(disposal);
        }

        // POST: Disposal/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

AssetMGT/Views/Disposal/Create.cshtml
@model AssetMGT.ViewModels.DisposalViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Disposal", null, FormMethod.Post,
                                          new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="card text-center">
            <div class="card-header">
                <h4>Dispose The Asset (@ViewBag.AssetName)</h4>
            </div>

            <div class="card-body">


                

                <div class=" row text-left ml-3">
                    <div class="col-md-3"></div>
                    <div class="col-md-7">
                        <dl class="dl-horizontal text-left">
                            <dt>
                                Disposal Currency
                            </dt>

                            <dd>
                               
                                    @Html.DropDownList("CurrencyId", new SelectList(Model.Currencies, "Value", "Text"), htmlAttributes: new { @class = "form-control", required = "true", @id="CurrencyId" })


                                <!--@@Html.DropDownList("CurrencyId", new SelectList(ViewBag.Currencies, "CurrencyName", "CurrencyName"), new { @@id = "CurrencyId" })
    @@Html.DropDownListFor(m => m.CurrencyId, (IEnumerable<SelectListItem>)ViewBag.Currencies)-->

                            </dd>

                            <dt>
                                Customer
                            </dt>

                            <dd>
                                @Html.DropDownList("CustomerId", new SelectList(Model.Customers, "Value", "Text"), htmlAttributes: new { @class = "form-control", required = "true", @id = "CustomerId" })


                            </dd>

                            <dt>
                                Asset Name
                            </dt>

                            <dd>
                                @foreach (var item in Model.Assets)
                                {
                                    @Html.EditorFor(modelItem => item.AssetName, item.AssetName, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })


                                }

                                <!--@@Html.EditorFor("AssetName", new { htmlAttributes = new { @@class = "form-control", required = true } })-->

                            </dd>

                            <dt>
                                Asset Code
                            </dt>

                            <dd>
                                @foreach (var item in Model.Assets)
                                {
                                    @Html.EditorFor(modelItem => item.AssetCode, item.AssetCode, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })

                                }

                                @foreach (var item in Model.Assets)
                                {
                                    <input type="hidden" value="@item.Id" name="AssetId" />

                                }


                            </dd>


                        </dl>
                        
                    </div>
                    
                    <div class="form-group col-md-2">
                        
                    </div>



                </div>

            </div>


            <div class="card-footer text-muted">


                <div class=" row">
                    <div class="form-group col-md-3"></div>
                    <div class="form-group col-md-6">

                        <input type="submit" value="Create" class="btn btn-success btn-sm" />

                        <a href="@Url.Action("Index","Disposal")" role="button" class="btn btn-primary btn-sm">&laquo; View Disposed Assets</a>

                    </div>

                    <div class="form-group col-md-3"></div>

                </div>


            </div>
        </div>



    </div>

    
}

AssetMGT/Views/Disposal/Delete.cshtml
@model AssetMGT.Data.Disposal

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>


<div>

    <div class="card text-center">
        <div class="card-header">
            <h4>Are you sure you want to delete this Disposal ?</h4>
        </div>
        <div class="card-body">

            <dl class="dl-horizontal">
                

                <dt>
                    @Html.DisplayNameFor(model => model.DisposalDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DisposalDate)
                </dd>

                


            </dl>

        </div>



        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="card-footer text-muted">
                <div class="form-group col-md-3"></div>
                <div class="form-group col-md-6">
                    <input type="submit" value="Delete" class="btn btn-default btn-sm" />

                    <a href="@Url.Action("Index","Disposal")" role="button" class="btn btn-primary btn-sm">Back To Disposal List</a>

                </div>

                <div class="form-group col-md-3"></div>
            </div>
        }

    </div>



    
</div>

AssetMGT/Views/Disposal/Details.cshtml
@model AssetMGT.Data.Asset

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<div>


    <div class="card text-center">
        <div class="card-header">
            <h4>Disposal Details of @ViewBag.AssetName</h4>
        </div>
        <div class="card-body text-left">
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <dl class="dl-horizontal text-left">
                    <dt class="text-left">
                        <b>Asset Code</b>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AssetCode)
                    </dd>
                    <dt class="text-left">
                        <b>Asset Name</b>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AssetName)
                    </dd>

                    <dt class="text-left">
                        <b>Asset Class</b>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AssetClass.AssetClassName)
                    </dd>

                    <dt class="text-left">
                        <b>Asset Purchase Date</b>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AssetPurchaseDate)
                    </dd>

                    <dt class="text-left">
                        Asset Disposal Date
                    </dt>

                    <dd>
                        @ViewBag.DisposalDate
                    </dd>



                </dl>
            </div>
        </div>
        <div class="card-footer text-muted">
            <div class="form-group col-md-3"></div>
            <div class="form-group col-md-6">

                <a href="@Url.Action("Index","Disposal")" role="button" class="btn btn-primary btn-sm">&laquo;Back To Disposal List</a>

            </div>

            <div class="form-group col-md-3"></div>
        </div>
    </div>


</div>

AssetMGT/Views/Disposal/Edit.cshtml
@model AssetMGT.Data.Disposal

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Disposal", null, FormMethod.Post,
                                          new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="card text-center">
            <div class="card-header">
                <h4>Edit Disposal Details for @ViewBag.AssetName</h4>
            </div>
            <div class="card-body">


                <div class=" row">

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.DisposalDate, htmlAttributes: new { @class = "control-label col-md-4" })

                        @Html.EditorFor(model => model.DisposalDate, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.DisposalDate, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.DisposalPrice, htmlAttributes: new { @class = "control-label col-md-4" })

                        @Html.EditorFor(model => model.DisposalPrice, new { htmlAttributes = new { @class = "form-control", @readonly="true" } })
                        @Html.ValidationMessageFor(model => model.DisposalPrice, "", new { @class = "text-danger" })

                    </div>

                </div>


                <div class=" row">

                    <div class="form-group col-md-6">
                        <b class="control-label col-md-4">Currency</b>
                        @Html.DropDownList("CurrencyId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CurrencyId, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group col-md-6">
                        <b class = "control-label col-md-4">Asset Name</b>
                       @Html.Editor("AssetName", new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.AssetName, @readonly = "true" } })


                    </div>

                </div>

                <div class=" row">

                    
                    <div class="form-group col-md-6">
                        <b class="control-label col-md-4">Asset Code</b>
                        @Html.Editor("AssetCode", new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.AssetCode, @readonly = "true" } })

                        @Html.ValidationMessageFor(model => model.AssetId, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group col-md-6">
                        <b class="control-label col-md-4">Customer Name</b>
                        @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })

                    </div>

                </div>


            </div>

            <div class="card-footer text-muted">
                <div class=" row">
                    <div class="form-group col-md-3"></div>
                    <div class="form-group col-md-6">
                        @Html.HiddenFor(model => model.Id, new { Value = Model.Id })
                        <input type="submit" value="Save" class="btn btn-info btn-sm" />

                        <a href="@Url.Action("Index","Disposal")" role="button" class="btn btn-primary btn-sm">&laquo; Back To Disposal List</a>

                    </div>

                    <div class="form-group col-md-3"></div>

                </div>
            </div>
        </div>
    </div>

}

AssetMGT/Views/Disposal/Index.cshtml
@model IEnumerable<AssetMGT.Data.Disposal>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Disposed Assets</h3>


<table class="table table-striped table-condensed  table-hover table-bordered">
    <tr>
        <th>
            AssetName
        </th>
        <th>
            AssetStatus
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisposalDate)
        </th>


        <th>Options</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Asset.AssetName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Asset.AssetStatus)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.DisposalDate)
        </td>


        <td>

            @Html.ActionLink("Details ", "Details", new { id = item.Id }, new { @class = "btn btn-primary btn-xs fa fa-list-alt " })
            @*@Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-outline-warning btn-xs fa fa-list-alt " })*@
        </td>
    </tr>
}

</table>