AssetMGT/Controllers/AssetLookups/CurrencyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetMGT.Data;
using AssetMGT.Service;
using AssetMGT.ViewModels;
using PagedList;
using static AssetMGT.Data.Currency;

namespace AssetMGT.Controllers.AssetLookups
{

    public class CurrencyController : Controller
    {
        private AssetMGTContext db = new AssetMGTContext();

        // GET: Currency
        [DynamicRoleAuthorize(ControllerName.Currency, ActionName.Index)]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, int? thepageSize)
        {
            //to enable search, page and sort
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrencyNameSorting = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.CurrencyCodeSorting = sortOrder == "CurrencyCode" ? "CurrencyCode_desc" : "CurrencyCode";
            ViewBag.CountrySorting = sortOrder == "Country" ? "Country_desc" : "Country";
            ViewBag.CurrentFilter = searchString;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }



            var viewModel = new AccountViewModel();
            viewModel.Currencies = db.Currencies;


            //searching functionality starts here
            if (!String.IsNullOrEmpty(searchString))
            {
                string realName = char.ToUpper(searchString[0]) + searchString.Substring(1);
                viewModel.Currencies = viewModel.Currencies.Where(s => s.CurrencyName.Contains(realName));
                ViewBag.SearchedItem = searchString;
            }

            //sort format
            switch (sortOrder)
            {
                case "name_desc":
                    viewModel.Currencies = viewModel.Currencies.OrderByDescending(s => s.CurrencyName);
                    break;
                case "CurrencyCode":
                    viewModel.Currencies = viewModel.Currencies.OrderBy(s => s.CurrencyCode);
                    break;
                case "CurrencyCode_desc":
                    viewModel.Currencies = viewModel.Currencies.OrderByDescending(s => s.CurrencyCode);
                    break;
                case "Country":
                    viewModel.Currencies = viewModel.Currencies.OrderBy(s => s.Country);
                    break;
                case "Country_desc":
                    viewModel.Currencies = viewModel.Currencies.OrderByDescending(s => s.Country);
                    break;

                default:
                    viewModel.Currencies = viewModel.Currencies.OrderBy(s => s.CurrencyName);
                    break;

            }

            int pageSize = (thepageSize ?? 10);
            int pageNumber = (page ?? 1);
            ViewBag.PageSize = pageSize;

            return View(viewModel.Currencies.ToPagedList(pageNumber, pageSize));
        }

        // GET: Currency/Details/5
        [DynamicRoleAuthorize(ControllerName.Currency, ActionName.Details)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Currency currency = db.Currencies.Find(id);
            if (currency == null)
            {
                return HttpNotFound();
            }
            return View(currency);
        }

        // GET: Currency/Create
        [DynamicRoleAuthorize(ControllerName.Currency, ActionName.Create)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Currency/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DynamicRoleAuthorize(ControllerName.Currency, ActionName.Create)]
        public ActionResult Create([Bind(Include = "Id,CurrencyName,CurrencyCode,Country")] Currency currency)
        {
            if (ModelState.IsValid)
            {
                db.Currencies.Add(currency);
                db.SaveChanges();

                //**************Create a transaction here and log the user****************//
                DateTime dateAndTime = DateTime.Now;
                string name = HttpContext.User.Identity.Name;
                ViewBag.Name = name;
                string action = "Created A Currency";
                string description = "A Currency whose Currency Code is " + currency.CurrencyCode + " and Currency Name is " + currency.CurrencyName + " was created";
                ActivityLogService activityLogService = new ActivityLogService();
                activityLogService.LogAction(db, action, description, name, dateAndTime);

                //*******************End of transaction***********************//

                return RedirectToAction("Index");
            }

            return View(currency);
        }

        // GET: Currency/Edit/5
        [DynamicRoleAuthorize(ControllerName.Currency, ActionName.Edit)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Currency currency = db.Currencies.Find(id);
            if (currency == null)
            {
                return HttpNotFound();
            }
            return View(currency);
        }

        // POST: Currency/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DynamicRoleAuthorize(ControllerName.Currency, ActionName.Edit)]
        public ActionResult Edit([Bind(Include = "Id,CurrencyName,CurrencyCode,Country")] Currency currency)
        {
            if (ModelState.IsValid)
            {
                db.Entry(currency).State = EntityState.Modified;
                db.SaveChanges();

                //**************Create a transaction here and log the user****************//
                DateTime dateAndTime = DateTime.Now;
                string name = HttpContext.User.Identity.Name;
                ViewBag.Name = name;
                string action = "Edited A Currency";
                string description = "A Currency whose Currency Code is " + currency.CurrencyCode + " and Currency Name is " + currency.CurrencyName + " was edited";
                ActivityLogService activityLogService = new ActivityLogService();
                activityLogService.LogAction(db, action, description, name, dateAndTime);

                //*******************End of transaction***********************//

                return RedirectToAction("Index");
            }
            return View(currency);
        }

        // GET: Currency/Delete/5
        [DynamicRoleAuthorize(ControllerName.Currency, ActionName.Delete)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Currency currency = db.Currencies.Find(id);
            if (currency == null)
            {
                return HttpNotFound();
            }
            return View(currency);
        }

        // POST: Currency/Delete/5
        [HttpPost, ActionName("Delete")]
        [DynamicRoleAuthorize(ControllerName.Currency, ActionName.Delete)]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Currency currency = db.Currencies.Find(id);
            db.Currencies.Remove(currency);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AssetMGT/Views/Currency/Create.cshtml
@model AssetMGT.Data.Currency

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="card text-center">
        <div class="card-header">
            <h4>Create New Currency</h4>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.CurrencyName, htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.EditorFor(model => model.CurrencyName, new { htmlAttributes = new { @class = "form-control", required = true } })
                    @Html.ValidationMessageFor(model => model.CurrencyName, "", new { @class = "text-danger" })


                </div>
                <div class="form-group col-md-6">

                    @Html.LabelFor(model => model.CurrencyCode, htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.EditorFor(model => model.CurrencyCode, new { htmlAttributes = new { @class = "form-control", required = true } })
                    @Html.ValidationMessageFor(model => model.CurrencyCode, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", required = true } })
                    @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })

                </div>

                <div class="col-md-3"></div>
           
            </div>
        </div>
        <div class="card-footer text-muted">
            <div class=" row">
                <div class="form-group col-md-3"></div>
                <div class="form-group col-md-6">
                    <input type="submit" value="Create" class="btn btn-success btn-sm" />

                    <a href="@Url.Action("Index","Currency")" role="button" class="btn btn-primary btn-sm">Back To Currency List</a>

                </div>

                <div class="form-group col-md-3"></div>

            </div>
        </div>
    </div>

}

AssetMGT/Views/Currency/Delete.cshtml
@model AssetMGT.Data.Currency

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<h3></h3>
<div>

    <div class="card text-center">
        <div class="card-header">
            <h4>Are you sure you want to delete this  Currency ?</h4>
        </div>
        <div class="card-body">

            <dl class="dl-horizontal">
                <dt>
                    Currency Name :
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CurrencyName)
                </dd>

                <dt>
                    Currency Code :
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CurrencyCode)
                </dd>

                <dt>
                    Country :
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Country)
                </dd>

            </dl>

        </div>



        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="card-footer text-muted">
                <div class="form-group col-md-3"></div>
                <div class="form-group col-md-6">
                    <input type="submit" value="Delete" class="btn btn-default btn-sm" />

                    <a href="@Url.Action("Index","Currency")" role="button" class="btn btn-primary btn-sm">Back To Currency List</a>

                </div>

                <div class="form-group col-md-3"></div>
            </div>
        }

    </div>
  
    
</div>

AssetMGT/Views/Currency/Details.cshtml
@model AssetMGT.Data.Currency

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<div>

    <div class="card text-center">
        <div class="card-header">
            <h4>Details of Currency</h4>
        </div>
        <div class="card-body">
            <dl class="dl-horizontal">
                <dt>
                    Currency Name :
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CurrencyName)
                </dd>

                <dt>
                    Currency Code :
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CurrencyCode)
                </dd>

                <dt>
                    Country :
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Country)
                </dd>

            </dl>
        </div>
        <div class="card-footer text-muted">
            <div class="form-group col-md-3"></div>
            <div class="form-group col-md-6">

                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-outline-primary btn-xs fa fa-pencil " }) |
                <a href="@Url.Action("Index","Currency")" role="button" class="btn btn-primary btn-sm">Back To Currency List</a>

            </div>

            <div class="form-group col-md-3"></div>
        </div>
    </div>

</div>

AssetMGT/Views/Currency/Edit.cshtml
@model AssetMGT.Data.Currency

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <div class="card text-center">
        <div class="card-header">
            <h4>Edit the Currency</h4>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.CurrencyName, htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.EditorFor(model => model.CurrencyName, new { htmlAttributes = new { @class = "form-control", required = true } })
                    @Html.ValidationMessageFor(model => model.CurrencyName, "", new { @class = "text-danger" })


                </div>
                <div class="form-group col-md-6">

                    @Html.LabelFor(model => model.CurrencyCode, htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.EditorFor(model => model.CurrencyCode, new { htmlAttributes = new { @class = "form-control", required = true } })
                    @Html.ValidationMessageFor(model => model.CurrencyCode, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", required = true } })
                    @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })

                </div>

                <div class="col-md-3"></div>

            </div>
        </div>

        <div class="card-footer text-muted">
            <div class=" row">
                <div class="form-group col-md-3"></div>
                <div class="form-group col-md-6">
                    <input type="submit" value="Save" class="btn btn-default btn-sm" />

                    <a href="@Url.Action("Index","Currency")" role="button" class="btn btn-primary btn-sm">Back To Currency List</a>

                </div>

                <div class="form-group col-md-3"></div>

            </div>
        </div>
    </div>
 </div>

}

AssetMGT/Views/Currency/Index.cshtml
@model PagedList.IPagedList<AssetMGT.Data.Currency>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Registered Currencies</h3>

<div class="card">
    <div class="card-header">
        <i class="fa fa-filter text-right" aria-hidden="true"></i>  Filters
    </div>
    <div class="card-body">
        @using (Html.BeginForm("../Currency/Index", "Currency", FormMethod.Get))
        {
            <div class="row">


                <div class="form-group col-md-3">
                    <label for="inputZip">Search Currency Name</label>
                    @*Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)*@
                    @Html.Editor("SearchString", ViewBag.CurrentFilter as string, new { htmlAttributes = new { @class = "form-control input-sm", @placeholder = "Search Currency Name..." } })
                </div>
                <div class="form-group col-md-3">
                    <label for="inputZip">Showing</label>
                    <input type="text" class="form-control input-sm" value="@ViewBag.PageSize" name="thepageSize" /> Records Per Page
                </div>
                <div class="form-group col-md-3">
                    <input type="submit" value="Filter" class="btn btn-info btn-sm" style="margin-top:25px;" />

                </div>
            </div>

        }

        <div class="row"></div>


    </div>
</div>
<br />

<p>
    <a href="@Url.Action("../Currency/Create","Currency")" class="btn btn-info btn-sm" role="button" aria-pressed="true">Register Currency</a>

</p>



<table class="table table-striped table-condensed  table-hover table-bordered">
    <tr>
        <th>
            @Html.ActionLink("Currency Name", "Index", new { sortOrder = ViewBag.CurrencyNameSorting, currentFilter = ViewBag.CurrentFilter })

        </th>
        <th>
            @Html.ActionLink("Currency Code", "Index", new { sortOrder = ViewBag.CurrencyCodeSorting, currentFilter = ViewBag.CurrentFilter })

        </th>
        <th>
            @Html.ActionLink("Country", "Index", new { sortOrder = ViewBag.CountrySorting, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>Options</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CurrencyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrencyCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>

                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-outline-primary btn-sm fa fa-pencil " })
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-outline-warning btn-sm fa fa-list-alt " })
            </td>
        </tr>
    }

</table>

  Showing Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, thepageSize = ViewBag.pageSize }))