AssetMGT/Controllers/DepreciationController.cs
using AssetMGT.Data;
using AssetMGT.Service;
using AssetMGT.ViewModels;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PagedList;

namespace AssetMGT.Controllers
{
    
    public class DepreciationController : Controller
    {
        private AssetMGTContext db = new AssetMGTContext();

        // GET: TestDepreciation
        [DynamicRoleAuthorize(ControllerName.Depreciation, ActionName.Index)]
        public ActionResult Index()
        {
           var depreciations = db.Depreciations.Include(d => d.Asset).Include(d => d.Currency);
            var Assets = db.Assets.Include(a => a.AssetClass);
            DepreciationDetailsViewModel depreciationDetailsViewModel = new DepreciationDetailsViewModel();
            depreciationDetailsViewModel.Assets = Assets;
            return View("DepreciationDetails",depreciationDetailsViewModel);
            //return View(depreciations.ToList());
        }

        // GET: TestDepreciation/Details/5
        [DynamicRoleAuthorize(ControllerName.Depreciation, ActionName.Details)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Depreciation depreciation = db.Depreciations.Find(id);
            if (depreciation == null)
            {
                return HttpNotFound();
            }
            return View(depreciation);
        }

        // GET: TestDepreciation/Create
        [DynamicRoleAuthorize(ControllerName.Depreciation, ActionName.Create)]
        public ActionResult Create()
        {
            ViewBag.AssetId = new SelectList(db.Assets, "Id", "AssetCode");
            ViewBag.CurrencyId = new SelectList(db.Currencies, "Id", "CurrencyName");
            return View();
        }

        // POST: TestDepreciation/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DynamicRoleAuthorize(ControllerName.Depreciation, ActionName.Create)]
        public ActionResult Create([Bind(Include = "Id,DepreciationMethod,DepreciationPercentage,salvageValue,DepreciationValue,NetbookValue,DepreciationPeriod,CurrencyId,AssetId")] Depreciation depreciation)
        {
            Asset asset = db.Assets.SingleOrDefault(a => a.Id == depreciation.AssetId);
            //getting the basevalue
            int purchaseprice = asset.AssetPurchasePrice;
            int salvagevalue = depreciation.salvageValue;
            int totaldepreciablecost = purchaseprice - salvagevalue;

            //getting the useful life
            DateTime purchasedate = asset.AssetPurchaseDate;
            int usefullife = DateTime.UtcNow.Year - purchasedate.Year;
            int depreciationamount = totaldepreciablecost / usefullife;
            int depPercentage = Convert.ToInt32((Convert.ToDouble(depreciationamount) / Convert.ToDouble(totaldepreciablecost)) * 100);
            int netbookvalue = purchaseprice - depreciationamount;


            if (ModelState.IsValid)
            {
                depreciation.DepreciationPercentage = depPercentage;
                depreciation.DepreciationValue = depreciationamount;
                depreciation.NetbookValue = netbookvalue;
                depreciation.DepreciationPeriod = usefullife;
                db.Depreciations.Add(depreciation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AssetId = new SelectList(db.Assets, "Id", "AssetCode", depreciation.AssetId);
            ViewBag.CurrencyId = new SelectList(db.Currencies, "Id", "CurrencyName", depreciation.CurrencyId);
            return View(depreciation);
        }

        // GET: TestDepreciation/Edit/5
        [DynamicRoleAuthorize(ControllerName.Depreciation, ActionName.Edit)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Depreciation depreciation = db.Depreciations.Find(id);
            if (depreciation == null)
            {
                return HttpNotFound();
            }
            ViewBag.AssetId = new SelectList(db.Assets, "Id", "AssetCode", depreciation.AssetId);
            ViewBag.CurrencyId = new SelectList(db.Currencies, "Id", "CurrencyName", depreciation.CurrencyId);
            return View(depreciation);
        }

        // POST: TestDepreciation/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DynamicRoleAuthorize(ControllerName.Depreciation, ActionName.Edit)]
        public ActionResult Edit([Bind(Include = "Id,DepreciationMethod,DepreciationPercentage,salvageValue,DepreciationValue,NetbookValue,DepreciationPeriod,CurrencyId,AssetId")] Depreciation depreciation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(depreciation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AssetId = new SelectList(db.Assets, "Id", "AssetCode", depreciation.AssetId);
            ViewBag.CurrencyId = new SelectList(db.Currencies, "Id", "CurrencyName", depreciation.CurrencyId);
            return View(depreciation);
        }

        // GET: TestDepreciation/Delete/5
        [DynamicRoleAuthorize(ControllerName.Depreciation, ActionName.Delete)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Depreciation depreciation = db.Depreciations.Find(id);
            if (depreciation == null)
            {
                return HttpNotFound();
            }
            return View(depreciation);
        }

        // POST: TestDepreciation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [DynamicRoleAuthorize(ControllerName.Depreciation, ActionName.Delete)]
        public ActionResult DeleteConfirmed(int id)
        {
            Depreciation depreciation = db.Depreciations.Find(id);
            db.Depreciations.Remove(depreciation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Depreciation/Details
        public ActionResult DuplicateDetails(string sortFormat, string searchString, int? page, int? id, string yearEntered,string textyearEntered, string assetClassId, string timefreq)
        {
            ViewBag.yearEntered = new SelectList(db.Assets.Where(y => y.AssetStatus == "Active").Select(y => y.StartDepreciationDate.Year).Distinct());
            

            ViewBag.CurrentFilter = searchString;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                //searchString = currentFilter;
            }
            ViewBag.assetClassId = new SelectList(db.AssetClasses, "Id", "AssetClassName");
            
            DepreciationDetailsViewModel assetDetailsViewModel = new DepreciationDetailsViewModel();
            

            if (timefreq == "Monthly")
            {
                if (!String.IsNullOrEmpty(assetClassId))
                {
                    int theAssetClassId = Convert.ToInt32(assetClassId);
                    assetDetailsViewModel.Assets = db.Assets.Where(d => d.AssetStatus == "Active").Include(a => a.AssetClass).Where(d => d.AssetClassId == theAssetClassId).Include(a => a.AssetIndicator).Include(a => a.Employee).Include(a => a.MaintenanceFrequency).Include(a => a.Supplier);
                    ViewBag.assetClassFilter = assetClassId;
                }
                else
                {
                    assetDetailsViewModel.Assets = db.Assets.Where(d => d.AssetStatus == "Active").Include(a => a.AssetClass).Include(a => a.AssetIndicator).Include(a => a.Employee).Include(a => a.MaintenanceFrequency).Include(a => a.Supplier);
                }

                // searching functionality starts here
                if (!String.IsNullOrEmpty(searchString))
                {
                    string realName = char.ToUpper(searchString[0]) + searchString.Substring(1);
                    assetDetailsViewModel.Assets = assetDetailsViewModel.Assets.Where(s => s.AssetName.Contains(realName));
                    ViewBag.SearchedItem = searchString;
                }

                bool isMonthly = true;
                ViewBag.isMonthly = isMonthly;
                List<Asset> assetList = new List<Asset>();
                int theNowYear;
                
                foreach (var item in assetDetailsViewModel.Assets)
                {
                    Asset asset = new Asset();
                    DateTime startDepreciationDate;
                    startDepreciationDate = item.StartDepreciationDate;
                    DateTime currentDate;

                    if (item.EndDepreciationDate != null)
                    {
                        currentDate = item.EndDepreciationDate.GetValueOrDefault();
                    }
                    else
                    {
                        currentDate = DateTime.UtcNow;
                    }

                    
                    theNowYear = currentDate.Year;
                    int startDepYear = startDepreciationDate.Year;
                    
                    int theEnteredYear = DateTime.Now.Year;

AssetMGT/Views/Depreciation/Create.cshtml
@model AssetMGT.Data.Depreciation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

         <div class="card text-center">
                <div class="card-header">
                    <h4>Register a New Depreciation</h4>
                </div>

                <div class="card-body">


                     <div class=" row">

                    <div class="form-group col-md-6">
                        @Html.HiddenFor(model => model.DepreciationMethod, new { Value = "Active" })
                        @Html.LabelFor(model => model.DepreciationMethod, htmlAttributes: new { @class = "control-label col-md-4" })

                        @Html.EditorFor(model => model.DepreciationMethod, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DepreciationMethod, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.salvageValue, htmlAttributes: new { @class = "control-label col-md-4" })

                        @Html.EditorFor(model => model.salvageValue, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.salvageValue, "", new { @class = "text-danger" })

                    </div>

                </div>


                <div class=" row">

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.CurrencyId, "CurrencyId", htmlAttributes: new { @class = "control-label col-md-4" })

                        @Html.DropDownList("CurrencyId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CurrencyId, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.AssetId, "AssetId", htmlAttributes: new { @class = "control-label col-md-4" })

                        @Html.DropDownList("AssetId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.AssetId, "", new { @class = "text-danger" })

                    </div>

                </div>





        </div>




        <div class="card-footer text-muted">


            <div class=" row">
                <div class="form-group col-md-3"></div>
                <div class="form-group col-md-6">
                    <input type="submit" value="Create" class="btn btn-success btn-sm" />

                    <a href="@Url.Action("Index","Depreciation")" role="button" class="btn btn-primary btn-sm">Back To Depreciation List</a>

                </div>

                <div class="form-group col-md-3"></div>

            </div>


        </div>
    </div>


        
        </div>
    

}

AssetMGT/Views/Depreciation/Delete.cshtml
@model AssetMGT.Data.Depreciation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<h3></h3>
<div>

    <div class="card text-center">
        <div class="card-header">
            <h4>Are you sure you want to delete this Depreciation ?</h4>
        </div>
        <div class="card-body">

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Asset.AssetCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Asset.AssetCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Currency.CurrencyName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Currency.CurrencyName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DepreciationMethod)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DepreciationMethod)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DepreciationPercentage)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DepreciationPercentage)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.salvageValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.salvageValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DepreciationValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DepreciationValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NetbookValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NetbookValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DepreciationPeriod)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DepreciationPeriod)
                </dd>

            </dl>

        </div>



        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="card-footer text-muted">
                <div class="form-group col-md-3"></div>
                <div class="form-group col-md-6">
                    <input type="submit" value="Delete" class="btn btn-default btn-sm" />

                    <a href="@Url.Action("Index","Depreciation")" role="button" class="btn btn-primary btn-sm">Back To Depreciation List</a>

                </div>

                <div class="form-group col-md-3"></div>
            </div>
        }

    </div>



 
</div>

AssetMGT/Views/Depreciation/DepreciationDetails.cshtml
@model AssetMGT.ViewModels.DepreciationDetailsViewModel

@{
    ViewBag.Title = "Depreciation Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Depreciation Report</h4>

<div class="row mb-2">
    @using (Html.BeginForm("DepreciationDetails", "Depreciation", FormMethod.Get))
    {
        <div class="col-md-12 text-left" style="display:flex;">

            <div class="form-group mr-3">
                <label for="inputState">Asset Class</label><br />
                @*@Html.TextBox("SearchString")*@
                @Html.DropDownList("AssetClassId", null, htmlAttributes: new { @class = "form-control input-sm", required = "true" })
            </div>
            <div class="form-group mr-3">
                <label for="inputState">Choose Monthly/Yearly</label>
                <select id="timefreq" class="form-control input-sm" name="timefreq" required>
                    <option value="Yearly">Yearly</option>
                    <option value="Monthly">Monthly</option>

                </select>
            </div>

            <div class="form-group ">
                <label for="inputZip">Enter Year</label>
                <input type="text" class="form-control input-sm" id="Year" name="YearEntered" placeholder="Eg 2014">
            </div>

            <div class="form-group ml-3">
                <label for="inputZip">Search asset</label>
                <input type="text" class="form-control input-sm" id="Year" name="searchString" placeholder="Search Asset...">
            </div>

            <div class="form-group">
                <input type="submit" value="Filter" style="margin-left:10px;margin-top:25px;width:80px;height:30px;" class="btn btn-primary btn-xm" />

            </div>

        </div>
    }
</div>

@if (Model.Assets == null)
{
<section id="yearTable">

    <div class="row mb-2">

        <div class="col-md-12 text-left" style="display:flex;">

            <!--***********************************The export yearly function**************************************-->

            @using (Html.BeginForm("DepList", "Depreciation", null, FormMethod.Post,
                                                                  new { enctype = "multipart/form-data" }))
            {
                <input type="hidden" value="@ViewBag.assetClassFilter" name="classFilter" />
                <input type="submit" value="Export to Excel" class="btn btn-success btn-sm" />

            }
        </div>

    </div>
    <hr />
    <h5> <b>Annual Depreciation Report</b></h5>
    <table class="table table-striped table-condensed  table-hover table-bordered table-responsive">
        @if(Model.AssetRegisterings.Count != 0)
        {

        <tr>
            <th></th>
            <th></th>
            @{
                int minimum = int.MaxValue;
            }
            @foreach (var year in Model.AssetRegisterings)
            {

                int dateStart = year.AssetPurchaseDate.Year;
                int TodayDate = DateTime.Now.Year;

                minimum = Math.Min(minimum, dateStart);
            }

            @{
                int myminimum = int.MaxValue;

                int mydateStart = minimum;
                int myTodayDate = DateTime.Now.Year;

                myminimum = Math.Min(myminimum, mydateStart);

                for (int count = myminimum; count < myTodayDate; count++)
                {

                    <th colspan="2">Year: @count</th>
                }
            }

        </tr>
        <tr>
            <th>Asset Name</th>
            <th>Dep %</th>

            @{
                int newminimum = int.MaxValue;

                int thisdateStart = minimum;
                int thisTodayDate = DateTime.Now.Year;

                newminimum = Math.Min(newminimum, thisdateStart);


                for (int count = (newminimum + 1); count <= myTodayDate; count++)
                {

                    <th>Dep Amount</th>
                    <th>NetBook Value</th>
                }

            }

        </tr>

        foreach (var asset in Model.AssetRegisterings)
        {

            <tr>
                <td>@asset.AssetName</td>
                <td>@asset.DepreciationPercentage</td>
                @{
                    int finaldateStart = asset.AssetPurchaseDate.Year;
                    int finalTodayDate = DateTime.Now.Year;


                    //  minimum = Math.Min(minimum, finaldateStart);
                }

                @foreach (var deprec in asset.AssetDepreciatings)
                {



                    <td>@deprec.DepreciationAmount</td>
                    <td>@deprec.NetBookValue</td>


                }
            </tr>
        }


                    }

    </table>

</section>
}

else if (Model.Assets != null)
{
<section id="MonthlyTable">
    <div class="row mb-2">

        <div class="col-md-12 text-left" style="display:flex;">

            <!--***********************************The export Monthly function**************************************-->

            @using (Html.BeginForm("DepMonthlyList", "Depreciation", null, FormMethod.Post,
                                                                  new { enctype = "multipart/form-data" }))
            {

                <input type="hidden" value="@ViewBag.assetClassFilter" name="classFilter" />
                <input type="hidden" value="@ViewBag.SearchedItem" name="SearchedItemFilter" />
                <input type="hidden" value="@ViewBag.Year" name="YearFilter" />
                <input type="submit" value="Export to Excel" class="btn btn-success btn-sm" />

            }
        </div>

    </div>
    <hr />
    <h5><b>Monthly Report in @ViewBag.Year</b></h5>


    <table class="table table-striped table-condensed table-hover table-bordered table-responsive" border="1">

        <tr>
            <th></th>
            <th></th>

            @for (int count = 1; count <= 12; count++)
            {
                <th colspan="2">Month: @count</th>
            }

        </tr>
        <tr>
            <th>Asset Name</th>
            <th>Dep %</th>
            @for (int count = 1; count <= 12; count++)
            {

                <th>Dep Amount</th>
                <th>NetBook Value</th>
            }

        </tr>
        @foreach (var item in Model.Assets)
        {
            <tr>
                <td style="width:600px">@item.AssetName</td>
                <td>@item.DepPercentage</td>
                @for (int c = 1; c <= 12; c++)
                {
                    int myItemDepreciation = Convert.ToInt32(item.DepAmount) / 12;
                    int myItemNetbookvalue = Convert.ToInt32(item.GrossAmount) / 12;
                    <td>@myItemDepreciation</td>
                    <td>@myItemNetbookvalue</td>
                }



            </tr>
        }

    </table>

</section>
}

@if (ViewBag.isMonthly == true)
{
    <script>
        //Hide or show the table of Depreciations

        $("#yearTable").hide();
        $("#MonthlyTable").show();
        $('#timefreq').val('Monthly');
    </script>
}
else
{
    <script>
        //Hide or show the table of Depreciations


        $(document).ready(function () {
            $("#MonthlyTable").hide();
            $("#yearTable").show();
        });

    </script>
}

AssetMGT/Views/Depreciation/Details.cshtml
@model AssetMGT.Data.Depreciation

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<div>


    <div class="card text-center">
        <div class="card-header">
            <h4>Details of Depreciation</h4>
        </div>
        <div class="card-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Asset.AssetCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Asset.AssetCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Currency.CurrencyName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Currency.CurrencyName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DepreciationMethod)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DepreciationMethod)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DepreciationPercentage)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DepreciationPercentage)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.salvageValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.salvageValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DepreciationValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DepreciationValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NetbookValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NetbookValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DepreciationPeriod)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DepreciationPeriod)
                </dd>

            </dl>
        </div>
        <div class="card-footer text-muted">
            <div class="form-group col-md-3"></div>
            <div class="form-group col-md-6">

                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-outline-primary btn-xs fa fa-pencil " }) |
                <a href="@Url.Action("Index","Depreciation")" role="button" class="btn btn-primary btn-sm">Back To Depreciation List</a>

            </div>

            <div class="form-group col-md-3"></div>
        </div>
    </div>


</div>

AssetMGT/Views/Depreciation/Edit.cshtml
@model AssetMGT.Data.Depreciation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <div class="card text-center">
        <div class="card-header">
            <h4>Edit the Depreciation</h4>
        </div>
        <div class="card-body">


            <div class=" row">

                <div class="form-group col-md-6">
                    @Html.HiddenFor(model => model.DepreciationMethod, new { Value = "Active" })
                    @Html.LabelFor(model => model.DepreciationMethod, htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.EditorFor(model => model.DepreciationMethod, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DepreciationMethod, "", new { @class = "text-danger" })

                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.salvageValue, htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.EditorFor(model => model.salvageValue, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.salvageValue, "", new { @class = "text-danger" })

                </div>

            </div>


            <div class=" row">

                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.CurrencyId, "CurrencyId", htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.DropDownList("CurrencyId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CurrencyId, "", new { @class = "text-danger" })

                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.AssetId, "AssetId", htmlAttributes: new { @class = "control-label col-md-4" })

                    @Html.DropDownList("AssetId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AssetId, "", new { @class = "text-danger" })

                </div>

            </div>


        </div>

        <div class="card-footer text-muted">
            <div class=" row">
                <div class="form-group col-md-3"></div>
                <div class="form-group col-md-6">
                    <input type="submit" value="Save" class="btn btn-default btn-sm" />

                    <a href="@Url.Action("Index","Depreciation")" role="button" class="btn btn-primary btn-sm">Back To Depreciation List</a>

                </div>

                <div class="form-group col-md-3"></div>

            </div>
        </div>
    </div>
</div>
}

AssetMGT/Views/Depreciation/Index.cshtml
@model IEnumerable<AssetMGT.Data.Depreciation>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Registered Depreciations</h3>

<p>
    <a href="@Url.Action("../Depreciation/Create","Depreciation")" class="btn btn-info btn-sm" role="button" aria-pressed="true">Register Depreciation</a>

</p>
<table class="table table-striped table-condensed  table-hover table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Asset.AssetName)
        </th>
        <th>
          Currency
        </th>
       
        <th>
           Depreciation %
        </th>
        <th>
            @Html.DisplayNameFor(model => model.salvageValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepreciationValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NetbookValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepreciationPeriod)
        </th>
        <th>Options</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Asset.AssetName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Currency.CurrencyCode)
        </td>
      
        <td>
            @Html.DisplayFor(modelItem => item.DepreciationPercentage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.salvageValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepreciationValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NetbookValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepreciationPeriod)
        </td>
        <td>
        
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-outline-primary btn-xs fa fa-pencil " })
            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-outline-warning btn-xs fa fa-list-alt " })
        
        </td>
    </tr>
}

</table>